id: P007956
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25006
  title: བོད་མིའི་ཡུལ་སྲོལ་གོམས་གཤིས།
  author: ''
  volumes:
    bd5f2331631e4d9fa7bd36eb085801a4:
      image_group_id: I1KG25008
      title: ''
      volume_number: 1
      total_pages: 170
ebook_metadata:
  title: བོད་མིའི་ཡུལ་སྲོལ་གོམས་གཤིས།
  author: ''
  sku: P007956
  cover: cover.jpg
  layers:
  - pagination
